### PR TITLE
fixing indentation automatically for all launch files using tidy

### PR DESCRIPTION
**Pull request by ugocupcic**

### CODE REVIEW

**Comment by toliver** [comment]
I have some doubts that this obsession with extra short lines actually makes things more readable. Same in python with the pep8.
Happy to merge anyway.

**Comment by ugocupcic** [comment]
@toliver I agree about short lines - I was more aiming to fix really bad indentation (we have huge variations in some launch files with an amazing number of spaces and it's quite hard to read). I can take a look at tidy, see if there's some option to use a longer line break?

**Comment by toliver** [comment]
That would  be good if there's an option. Unless other people prefer the shorter lines for a good reason.

**Comment by ugocupcic** [comment]
@toliver done (I used `-w 200` to specify a go to line at column 200)

**Pull request merged**
