### PR TITLE
B fix simulation

### LINKED ISSUE #157: hand simulation not working with gazebo 1.9.6 on hydro
This is mainly due to wrong inertia parameters in the hand model. They don't work any more with gazebo 1.9.6.

### PR DESCRIPTION
**Pull request by toliver**
Fixes #157

The changes have been hand picked from @guihomework  changes in 5ee2b6dff9508bf005f852f9103132faedba1a2f

This PR mainly:
- Changes mass and inertia parameters
- Changes dynamics damping param
- Changes the limits of the joints

### CODE REVIEW

**Comment by toliver** [comment]
Tested with normal, left-normal, biotacs and ellipsoid (nano17) hand models.

**Comment by guihomework** [comment]
Regarding the arm description, it seems the efforts limits are still really huge here (1000). It would be better to stay with smaller values and take all the arm settings (xacro + controller tuning) from indigo too. Be aware the inertia values and controllers have been reworked for arm and hand in indigo; they might match better than the older commit referenced.

**Comment by toliver** [comment]
I didn't pick the arm changes, as @shadowmanos tells me that the arm simulation doesn't work on Indigo either.

EDIT: Sorry I just read more carefully your comment. I'll check the latest version for Indigo.

**Comment by toliver** [comment]
I added the changes in the arm description, and the simulated arm seems to work well.

**Pull request merged**
