### PR TITLE
added get min max from urdf to hand commander

### PR DESCRIPTION
**Pull request by ugocupcic**

### CODE REVIEW

**Comment by ugocupcic** [comment]
Just a quick note on this one: the indentation was bad and some lines contained whitespaces at the end. This creates some confusion when reading the diff. What should I do in this case? First merge with proper indentation under B_bad_indent, then propose the real code review?

**Comment by toliver** [comment]
I think this should definitely be the way to do it. Two separate branches one for indentation the other for real changes. Otherwise it's much ore difficult to review.

**Comment by ugocupcic** [comment]
OK will do this next time. sorry.

**Comment by toliver** [comment]
The hand commander is not using the get_min_max function internally (only the test uses it), but I guess you will use it somewhere else.

**Comment by ugocupcic** [comment]
yes, I'm upgrading sr_movements to be easier to use. It will be used in sr_movements (which was not using the hand commander yet), so that one can pass only the joint name for running the movement. This will simplify the code for self_tests a lot.

**Comment by toliver** [comment]
Sounds good. :)

**Pull request merged**
