### PR TITLE
Fixed the arm model for the latest gazebo 1.9.3 update...

### PR DESCRIPTION
**Pull request by ugocupcic**
Et voila!

file:///home/ugo/Pictures/Screenshot%20from%202014-01-28%2013:09:04.png

### CODE REVIEW

**Comment by markpitchless** [comment]
Works for me as well. Is there supposed to be a big gap on the shoulder joint and on the hand to arm connection?
 arm_and_hand_gazebo_gaps

**Comment by ugocupcic** [comment]
No. I did that quickly during the meeting so some of the coordinates must
be wrong.

On 28 January 2014 14:05, Mark Pitchless notifications@github.com wrote:

> Works for me as well. Is there supposed to be a big gap on the shoulder
> joint and on the hand to arm connection?
> [image: arm_and_hand_gazebo_gaps]https://f.cloud.github.com/assets/193641/2019118/cc1cef3e-881c-11e3-931b-bdbf99fdddd1.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ros-interface/pull/74#issuecomment-33476229
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by markpitchless** [comment]
Thought so, I'll do a quick fix.
Btw, this new gazebo is still pretty unstable, it doesn't take much for it to break the sim and cause the arm to collapse into a pile of parts again. E.g. just removing the support column from the launch (although deleting after the thing is up and running is fine). Seems to be the flailing around the arm does as it loads!

**Comment by ugocupcic** [comment]
Fixed bad offsets:
screenshot from 2014-01-30 15 49 17

**Pull request merged**
