### PR TITLE
Add the missing mesh for the finger biotac adapter.

### PR DESCRIPTION
**Pull request by toliver**
Not tested.

To test (on indigo):

export BIOTAC_HAND=1
roslaunch sr_hand gazebo_hand.launch

And check that the biotac adapters (not the same as the biotac sensors) show in the gazebo simulation.

### CODE REVIEW

**Comment by toliver** [comment]
Why has this been deleted?

**Comment by toliver** [comment]
This branch has to be merged to Indigo.

**Comment by markpitchless** [comment]
Model looks good under indigo but can't seem to move the fingers with the sliders. Checking.

**Comment by markpitchless** [comment]
Same on machine at home, the non-biotac hand works as expected, the biotac hand looks right in Rviz but it doesn't move with the sliders.
Note: running in vm

**Comment by markpitchless** [comment]
The meshes look good. The biotac hand is broken in gazebo but also on indigo-devel so that is no change!

**Pull request merged**
